### ISSUE TITLE
jwt DecodeError: Not enough segments

### ISSUE THREAD

**Issue by shahriarsohan** [langchain-ai/helm#311]
Hello,

Following the docs mentioned [here](https://langchain-ai.github.io/langgraph/cloud/deployment/standalone_container/#kubernetes-helm) .

Here is my `langgraph_cloud_config.yaml`

```
images:
  apiServerImage:
    repository: trump/rocks
    tag: latest
    pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: dockerhub-secret

config:
  langGraphCloudLicenseKey: "added_correct_key"

apiServer:
  deployment:
    imagePullSecrets:
      - name: dockerhub-secret
  env:
    - name: POSTGRES_URI
      value: "also_added_correct_postgres_uri"
    - name: REDIS_URI
      value: "same_here"
    - name: LANGSMITH_API_KEY
      value: "added_correct_key [duplicate because i'm confused]"
  


postgres:
  external:
    enabled: true
    connectionUrl: "also_added_correct_postgres_uri"
````

But when upgrading the helm chart with the above config file i am getting the following error

```
    raise DecodeError("Not enough segments") from err
jwt.exceptions.DecodeError: Not enough segments
 [uvicorn.error] api_revision=c6b789f api_variant=licensed thread_name=MainThread
2025-05-20T17:03:08.064870Z [error    ] Application startup failed. Exiting. [uvicorn.error] api_revision=c6b789f api_variant=licensed thread_name=MainThread
```

from my understanding i think its related to LANGSMITH_API_KEY or LANGGRAPH_CLOUD_LICENSE_KEY, although i am using [Lite](https://langchain-ai.github.io/langgraph/concepts/langgraph_server/#server-versions).

Trying to fix this for last three hours, Let me know i f anything needed to debug furthur. Thanks in advance
