### ISSUE TITLE
Support persistentVolumeClaimRetentionPolicy

### ISSUE THREAD

**Issue by snoop123** [langchain-ai/helm#332]
Hi!
It would be very helpful if you could support `persistentVolumeClaimRetentionPolicy` in langgraph-cloud helm chart, for example:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: <NAME>
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
```

Thank you
